Avoid encoding binary with hex code directly (for py3)
1. [Python 3 disallows calling encode on bytes][1] resulting in: `AttributeError: 'bytes' object has no attribute 'encode'`
2. Use of `binascii` since "hex" codec is [dropped in some Py3 versions][2].

[1]: https://docs.python.org/3/howto/pyporting.html#text-versus-binary-data
[2]: http://stackoverflow.com/a/2340358/484127

P.S.: I know it's much digging for 1 liner logger change, but I was curious